[package]
name = "krugg-model"
publish = false
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["ted@ted.ooo"]
repository = "https://github.com/tedbyron/krugg"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
ugg-types = "0.7.0"
