[default]
description = "Allows making requests to the LCU API"
permissions = [
    "allow-connected",
    "allow-get-current-summoner",
    "allow-get-current-rune-page",
    "allow-update-rune-page",
]
